name: Trigger auto deployment for stackedit

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/stackedit-AutoDeployTrigger-8d48b0c7-78df-4261-b4d1-bec718017929.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.STACKEDIT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: handler.azurecr.io
          registryUsername: ${{ secrets.STACKEDIT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.STACKEDIT_REGISTRY_PASSWORD }}
          containerAppName: stackedit
          resourceGroup: chatlog
          imageToBuild: handler.azurecr.io/stackedit:${{ github.sha }}
          
            

     

